# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 182a4a666f13fbb1640d031396be15f528508f4e91ac01df00b7290d386b4c98e09eda5b206038a530b3b5fea093a262d48285ad88e05846182700b52fea5227

test:
  secret_key_base: dbc2842aa3b7141cba87ab352b8aa17cc857ca312ae301489545eacd75fe2aae970f0a67de30449cd6ad1f1685e9ee58cfabe69e7c7ab49fc46246e3d142e3b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
